// Individual food court stall entries — each stall is its own outlet.
// hawkerLocation / hawkerLocationId link each stall to its parent food court chain.
// outletType: 'food_court_stall' — individual counter inside a food court.
// All macros: source 'hpb', confidence 'estimated', verified: false.
// Meals are attributed to the STALL (e.g. "Chicken Rice Stall"), not the operator ("Koufu").

import type { SGRestaurant } from './sgFoodDb';

export const SG_FOOD_COURT_PLACES: SGRestaurant[] = [

  // ═══════════════════════════════════════════════════════════════
  // KOUFU
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'koufu_chicken_rice_stall',
    name: 'Chicken Rice Stall',
    emoji: '🍗',
    cuisine: 'Chinese',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['chicken rice koufu', 'koufu chicken rice'],
    dietTags: ['lactose_free'],
    priceRange: '$',
    hawkerLocation: 'Koufu',
    hawkerLocationId: 'koufu',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kfc_steamed_cr',  name: 'Steamed Chicken Rice',  emoji: '🍗', price: 4.00, calories: 607, protein: 35, carbs: 74, fat: 17, category: 'Rice',    compatibleWith: ['lactose_free'], isPopular: true,  macroDbRef: 'macro_chicken_rice_steamed',  confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kfc_roasted_cr',  name: 'Roasted Chicken Rice',  emoji: '🍗', price: 4.00, calories: 650, protein: 36, carbs: 76, fat: 20, category: 'Rice',    compatibleWith: ['lactose_free'], isPopular: false, macroDbRef: 'macro_chicken_rice_roasted', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kfc_char_siew_r', name: 'Char Siew Rice',        emoji: '🍖', price: 4.50, calories: 660, protein: 30, carbs: 76, fat: 20, category: 'Rice',    compatibleWith: ['lactose_free'], isPopular: false, macroDbRef: 'macro_char_siew_rice',       confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'koufu_mixed_veg_rice_stall',
    name: 'Mixed Veg Rice',
    emoji: '🍱',
    cuisine: 'Local',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['mixed veg rice koufu', 'cai png koufu', 'economy rice koufu'],
    dietTags: ['vegetarian', 'halal'],
    priceRange: '$',
    hawkerLocation: 'Koufu',
    hawkerLocationId: 'koufu',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kmvr_2dish',  name: 'Mixed Veg Rice (2 dishes)', emoji: '🍱', price: 3.50, calories: 390, protein: 14, carbs: 55, fat: 12, category: 'Rice', compatibleWith: ['vegetarian'], isPopular: false, macroDbRef: 'macro_mixed_veg_rice_2',  confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kmvr_3dish',  name: 'Mixed Veg Rice (3 dishes)', emoji: '🍱', price: 4.50, calories: 480, protein: 18, carbs: 65, fat: 16, category: 'Rice', compatibleWith: ['vegetarian'], isPopular: true,  macroDbRef: 'macro_mixed_veg_rice_3',  confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kmvr_4dish',  name: 'Mixed Veg Rice (4 dishes)', emoji: '🍱', price: 5.50, calories: 570, protein: 22, carbs: 74, fat: 20, category: 'Rice', compatibleWith: [],             isPopular: false, macroDbRef: 'macro_mixed_veg_rice_4',  confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'koufu_wonton_noodle_stall',
    name: 'Wonton Noodle Stall',
    emoji: '🍜',
    cuisine: 'Chinese',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['wonton mee koufu', 'wonton noodle koufu'],
    dietTags: ['lactose_free'],
    priceRange: '$',
    hawkerLocation: 'Koufu',
    hawkerLocationId: 'koufu',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kwn_dry',   name: 'Wonton Mee (Dry)',  emoji: '🍜', price: 4.00, calories: 434, protein: 22, carbs: 58, fat: 12, category: 'Noodles', compatibleWith: ['lactose_free'], isPopular: true,  macroDbRef: 'macro_wonton_mee',       confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kwn_soup',  name: 'Wonton Mee (Soup)', emoji: '🍲', price: 4.00, calories: 400, protein: 22, carbs: 54, fat: 10, category: 'Noodles', compatibleWith: ['lactose_free'], isPopular: false, macroDbRef: 'macro_wonton_mee_soup',  confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'koufu_laksa_stall',
    name: 'Laksa Corner',
    emoji: '🍲',
    cuisine: 'Local',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['laksa koufu', 'koufu laksa', 'mee siam koufu'],
    dietTags: ['halal'],
    priceRange: '$',
    hawkerLocation: 'Koufu',
    hawkerLocationId: 'koufu',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'klak_laksa',    name: 'Laksa',    emoji: '🍲', price: 4.50, calories: 589, protein: 27, carbs: 68, fat: 22, category: 'Noodles', compatibleWith: ['halal'], isPopular: true,  macroDbRef: 'macro_laksa',    confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'klak_meesiam', name: 'Mee Siam', emoji: '🍜', price: 4.00, calories: 450, protein: 16, carbs: 66, fat: 14, category: 'Noodles', compatibleWith: ['halal'], isPopular: false, macroDbRef: 'macro_mee_siam', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'koufu_nasi_lemak_stall',
    name: 'Nasi Lemak',
    emoji: '🍚',
    cuisine: 'Malay',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['nasi lemak koufu', 'koufu nasi lemak'],
    dietTags: ['halal'],
    priceRange: '$',
    hawkerLocation: 'Koufu',
    hawkerLocationId: 'koufu',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'knl_basic',   name: 'Nasi Lemak (basic)',        emoji: '🍚', price: 4.00, calories: 494, protein: 14, carbs: 60, fat: 22, category: 'Rice', compatibleWith: ['halal'], isPopular: true,  macroDbRef: 'macro_nasi_lemak',          confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'knl_chicken', name: 'Nasi Lemak with Chicken',   emoji: '🍗', price: 5.50, calories: 680, protein: 30, carbs: 62, fat: 30, category: 'Rice', compatibleWith: ['halal'], isPopular: false, macroDbRef: 'macro_nasi_lemak_chicken', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'koufu_ban_mian_stall',
    name: 'Ban Mian',
    emoji: '🍜',
    cuisine: 'Chinese',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['ban mian koufu', 'koufu ban mian', 'mee hoon kueh koufu'],
    dietTags: ['lactose_free'],
    priceRange: '$',
    hawkerLocation: 'Koufu',
    hawkerLocationId: 'koufu',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kbm_ban_mian',      name: 'Ban Mian',               emoji: '🍜', price: 4.50, calories: 460, protein: 22, carbs: 64, fat: 12, category: 'Noodles', compatibleWith: ['lactose_free'], isPopular: true,  macroDbRef: 'macro_ban_mian',         confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kbm_fish_ball',     name: 'Fish Ball Noodle Soup',  emoji: '🍲', price: 4.00, calories: 382, protein: 19, carbs: 60, fat: 6,  category: 'Noodles', compatibleWith: ['lactose_free'], isPopular: false, macroDbRef: 'macro_fishball_noodles', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'koufu_char_kway_teow_stall',
    name: 'Char Kway Teow',
    emoji: '🍜',
    cuisine: 'Chinese',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['char kway teow koufu', 'ckt koufu', 'hokkien mee koufu'],
    dietTags: ['lactose_free'],
    priceRange: '$',
    hawkerLocation: 'Koufu',
    hawkerLocationId: 'koufu',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kckt_ckt',         name: 'Char Kway Teow',  emoji: '🍜', price: 4.50, calories: 660, protein: 20, carbs: 82, fat: 26, category: 'Noodles', compatibleWith: [], isPopular: true,  macroDbRef: 'macro_char_kway_teow', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kckt_hokkien_mee', name: 'Hokkien Mee',     emoji: '🍜', price: 5.00, calories: 570, protein: 24, carbs: 68, fat: 20, category: 'Noodles', compatibleWith: [], isPopular: false, macroDbRef: 'macro_hokkien_mee',    confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'koufu_drinks_stall',
    name: 'Drinks Corner',
    emoji: '☕',
    cuisine: 'Drinks',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['drinks koufu', 'koufu drinks', 'kopi koufu', 'teh koufu'],
    dietTags: ['halal', 'vegan'],
    priceRange: '$',
    hawkerLocation: 'Koufu',
    hawkerLocationId: 'koufu',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kdrk_kopi_o',      name: 'Kopi O (Black Coffee)',        emoji: '☕', price: 1.20, calories: 15,  protein: 0, carbs: 3,  fat: 0, category: 'Drinks', compatibleWith: ['vegan', 'halal', 'gluten_free', 'lactose_free'], isPopular: true,  macroDbRef: 'macro_kopi_o',    confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kdrk_kopi',        name: 'Kopi (Coffee with Milk)',      emoji: '☕', price: 1.30, calories: 80,  protein: 2, carbs: 12, fat: 2, category: 'Drinks', compatibleWith: ['halal', 'gluten_free'],                           isPopular: false, macroDbRef: 'macro_kopi',     confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kdrk_teh_tarik',   name: 'Teh Tarik',                   emoji: '🥤', price: 1.50, calories: 112, protein: 4, carbs: 18, fat: 3, category: 'Drinks', compatibleWith: ['halal', 'gluten_free'],                           isPopular: true,  macroDbRef: 'macro_teh_tarik', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kdrk_milo',        name: 'Milo (Hot)',                   emoji: '🥤', price: 1.60, calories: 140, protein: 3, carbs: 26, fat: 3, category: 'Drinks', compatibleWith: ['halal', 'gluten_free'],                           isPopular: false, macroDbRef: 'macro_milo',     confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // KOPITIAM (NTUC Kopitiam)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'kopitiam_chicken_rice_stall',
    name: 'Chicken Rice Stall',
    emoji: '🍗',
    cuisine: 'Chinese',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['chicken rice kopitiam', 'kopitiam chicken rice', 'ntuc kopitiam chicken rice'],
    dietTags: ['lactose_free'],
    priceRange: '$',
    hawkerLocation: 'Kopitiam',
    hawkerLocationId: 'kopitiam',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kopicr_steamed', name: 'Steamed Chicken Rice', emoji: '🍗', price: 4.00, calories: 607, protein: 35, carbs: 74, fat: 17, category: 'Rice', compatibleWith: ['lactose_free'], isPopular: true,  macroDbRef: 'macro_chicken_rice_steamed',  confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kopicr_roasted', name: 'Roasted Chicken Rice', emoji: '🍗', price: 4.00, calories: 650, protein: 36, carbs: 76, fat: 20, category: 'Rice', compatibleWith: ['lactose_free'], isPopular: false, macroDbRef: 'macro_chicken_rice_roasted', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'kopitiam_mixed_veg_rice_stall',
    name: 'Mixed Veg Rice',
    emoji: '🍱',
    cuisine: 'Local',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['cai png kopitiam', 'economy rice kopitiam', 'mixed rice kopitiam'],
    dietTags: ['vegetarian', 'halal'],
    priceRange: '$',
    hawkerLocation: 'Kopitiam',
    hawkerLocationId: 'kopitiam',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kopimvr_2dish', name: 'Mixed Veg Rice (2 dishes)', emoji: '🍱', price: 3.50, calories: 390, protein: 14, carbs: 55, fat: 12, category: 'Rice', compatibleWith: ['vegetarian'], isPopular: false, macroDbRef: 'macro_mixed_veg_rice_2', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kopimvr_3dish', name: 'Mixed Veg Rice (3 dishes)', emoji: '🍱', price: 4.50, calories: 480, protein: 18, carbs: 65, fat: 16, category: 'Rice', compatibleWith: ['vegetarian'], isPopular: true,  macroDbRef: 'macro_mixed_veg_rice_3', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'kopitiam_noodle_stall',
    name: 'Noodle Corner',
    emoji: '🍜',
    cuisine: 'Chinese',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['noodle kopitiam', 'ban mian kopitiam', 'wonton mee kopitiam'],
    dietTags: ['lactose_free'],
    priceRange: '$',
    hawkerLocation: 'Kopitiam',
    hawkerLocationId: 'kopitiam',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kopinod_wonton',   name: 'Wonton Mee (Dry)',  emoji: '🍜', price: 4.00, calories: 434, protein: 22, carbs: 58, fat: 12, category: 'Noodles', compatibleWith: ['lactose_free'], isPopular: true,  macroDbRef: 'macro_wonton_mee',  confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kopinod_ban_mian', name: 'Ban Mian',          emoji: '🍜', price: 4.50, calories: 460, protein: 22, carbs: 64, fat: 12, category: 'Noodles', compatibleWith: ['lactose_free'], isPopular: false, macroDbRef: 'macro_ban_mian',    confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kopinod_fishball', name: 'Fishball Noodle',   emoji: '🍲', price: 4.00, calories: 382, protein: 19, carbs: 60, fat: 6,  category: 'Noodles', compatibleWith: ['lactose_free'], isPopular: false, macroDbRef: 'macro_fishball_noodles', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'kopitiam_laksa_stall',
    name: 'Laksa & Curry',
    emoji: '🍲',
    cuisine: 'Local',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['laksa kopitiam', 'curry noodle kopitiam', 'kopitiam laksa'],
    dietTags: ['halal'],
    priceRange: '$',
    hawkerLocation: 'Kopitiam',
    hawkerLocationId: 'kopitiam',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kopilak_laksa',   name: 'Laksa',         emoji: '🍲', price: 4.50, calories: 589, protein: 27, carbs: 68, fat: 22, category: 'Noodles', compatibleWith: ['halal'], isPopular: true,  macroDbRef: 'macro_laksa',        confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kopilak_curry_n', name: 'Curry Noodle',  emoji: '🍜', price: 4.50, calories: 520, protein: 22, carbs: 60, fat: 20, category: 'Noodles', compatibleWith: ['halal'], isPopular: false, macroDbRef: 'macro_curry_noodle', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'kopitiam_nasi_lemak_stall',
    name: 'Nasi Lemak',
    emoji: '🍚',
    cuisine: 'Malay',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['nasi lemak kopitiam', 'kopitiam nasi lemak'],
    dietTags: ['halal'],
    priceRange: '$',
    hawkerLocation: 'Kopitiam',
    hawkerLocationId: 'kopitiam',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kopinl_basic',   name: 'Nasi Lemak (basic)',      emoji: '🍚', price: 4.00, calories: 494, protein: 14, carbs: 60, fat: 22, category: 'Rice', compatibleWith: ['halal'], isPopular: true,  macroDbRef: 'macro_nasi_lemak',          confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kopinl_chicken', name: 'Nasi Lemak with Chicken', emoji: '🍗', price: 5.50, calories: 680, protein: 30, carbs: 62, fat: 30, category: 'Rice', compatibleWith: ['halal'], isPopular: false, macroDbRef: 'macro_nasi_lemak_chicken', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'kopitiam_western_stall',
    name: 'Western Stall',
    emoji: '🍽️',
    cuisine: 'Western',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['western kopitiam', 'chicken chop kopitiam', 'fish chips kopitiam'],
    dietTags: ['lactose_free'],
    priceRange: '$',
    hawkerLocation: 'Kopitiam',
    hawkerLocationId: 'kopitiam',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kopiwest_chop',    name: 'Chicken Chop',          emoji: '🍗', price: 6.50, calories: 560, protein: 38, carbs: 30, fat: 30, category: 'Mains', compatibleWith: ['lactose_free'], isPopular: true,  macroDbRef: 'macro_chicken_chop',  confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kopiwest_fish',    name: 'Fish & Chips',          emoji: '🐟', price: 6.50, calories: 600, protein: 30, carbs: 55, fat: 28, category: 'Mains', compatibleWith: [],               isPopular: false, macroDbRef: 'macro_fish_chips',    confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kopiwest_pasta',   name: 'Pasta (Aglio Olio)',    emoji: '🍝', price: 6.00, calories: 520, protein: 16, carbs: 72, fat: 18, category: 'Mains', compatibleWith: ['vegetarian'],   isPopular: false, macroDbRef: 'macro_aglio_olio',    confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'kopitiam_drinks_stall',
    name: 'Drinks Corner',
    emoji: '☕',
    cuisine: 'Drinks',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['drinks kopitiam', 'kopi kopitiam', 'teh kopitiam'],
    dietTags: ['halal', 'vegan'],
    priceRange: '$',
    hawkerLocation: 'Kopitiam',
    hawkerLocationId: 'kopitiam',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'kopidrk_kopi_o',    name: 'Kopi O',      emoji: '☕', price: 1.20, calories: 15,  protein: 0, carbs: 3,  fat: 0, category: 'Drinks', compatibleWith: ['vegan', 'halal', 'gluten_free', 'lactose_free'], isPopular: true,  macroDbRef: 'macro_kopi_o',     confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kopidrk_teh_tarik', name: 'Teh Tarik',   emoji: '🥤', price: 1.50, calories: 112, protein: 4, carbs: 18, fat: 3, category: 'Drinks', compatibleWith: ['halal', 'gluten_free'],                           isPopular: true,  macroDbRef: 'macro_teh_tarik', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'kopidrk_milo',      name: 'Milo (Hot)',  emoji: '🥤', price: 1.60, calories: 140, protein: 3, carbs: 26, fat: 3, category: 'Drinks', compatibleWith: ['halal', 'gluten_free'],                           isPopular: false, macroDbRef: 'macro_milo',      confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // NTUC FOODFARE
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'foodfare_chicken_rice_stall',
    name: 'Chicken Rice Stall',
    emoji: '🍗',
    cuisine: 'Chinese',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['chicken rice foodfare', 'foodfare chicken rice', 'ntuc foodfare chicken rice'],
    dietTags: ['lactose_free'],
    priceRange: '$',
    hawkerLocation: 'NTUC Foodfare',
    hawkerLocationId: 'ntuc_foodfare',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'ffcr_steamed', name: 'Steamed Chicken Rice', emoji: '🍗', price: 4.00, calories: 607, protein: 35, carbs: 74, fat: 17, category: 'Rice', compatibleWith: ['lactose_free'], isPopular: true,  macroDbRef: 'macro_chicken_rice_steamed',  confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'ffcr_roasted', name: 'Roasted Chicken Rice', emoji: '🍗', price: 4.00, calories: 650, protein: 36, carbs: 76, fat: 20, category: 'Rice', compatibleWith: ['lactose_free'], isPopular: false, macroDbRef: 'macro_chicken_rice_roasted', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'foodfare_mixed_veg_rice_stall',
    name: 'Mixed Veg Rice',
    emoji: '🍱',
    cuisine: 'Local',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['cai png foodfare', 'economy rice foodfare', 'mixed rice foodfare'],
    dietTags: ['vegetarian', 'halal'],
    priceRange: '$',
    hawkerLocation: 'NTUC Foodfare',
    hawkerLocationId: 'ntuc_foodfare',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'ffmvr_2dish', name: 'Mixed Veg Rice (2 dishes)', emoji: '🍱', price: 3.50, calories: 390, protein: 14, carbs: 55, fat: 12, category: 'Rice', compatibleWith: ['vegetarian'], isPopular: false, macroDbRef: 'macro_mixed_veg_rice_2', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'ffmvr_3dish', name: 'Mixed Veg Rice (3 dishes)', emoji: '🍱', price: 4.50, calories: 480, protein: 18, carbs: 65, fat: 16, category: 'Rice', compatibleWith: ['vegetarian'], isPopular: true,  macroDbRef: 'macro_mixed_veg_rice_3', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'foodfare_noodle_stall',
    name: 'Noodle Stall',
    emoji: '🍜',
    cuisine: 'Chinese',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['noodle foodfare', 'char kway teow foodfare', 'mee goreng foodfare'],
    dietTags: ['halal'],
    priceRange: '$',
    hawkerLocation: 'NTUC Foodfare',
    hawkerLocationId: 'ntuc_foodfare',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'ffnod_ckt',        name: 'Char Kway Teow', emoji: '🍜', price: 4.50, calories: 660, protein: 20, carbs: 82, fat: 26, category: 'Noodles', compatibleWith: [],       isPopular: true,  macroDbRef: 'macro_char_kway_teow', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'ffnod_mee_goreng', name: 'Mee Goreng',     emoji: '🍜', price: 4.50, calories: 520, protein: 18, carbs: 72, fat: 16, category: 'Noodles', compatibleWith: ['halal'], isPopular: false, macroDbRef: 'macro_mee_goreng',     confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'ffnod_mee_rebus',  name: 'Mee Rebus',      emoji: '🍲', price: 4.50, calories: 480, protein: 18, carbs: 72, fat: 14, category: 'Noodles', compatibleWith: ['halal'], isPopular: false, macroDbRef: 'macro_mee_rebus',      confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'foodfare_laksa_stall',
    name: 'Laksa Corner',
    emoji: '🍲',
    cuisine: 'Local',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['laksa foodfare', 'foodfare laksa'],
    dietTags: ['halal'],
    priceRange: '$',
    hawkerLocation: 'NTUC Foodfare',
    hawkerLocationId: 'ntuc_foodfare',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'fflak_laksa',    name: 'Laksa',    emoji: '🍲', price: 4.50, calories: 589, protein: 27, carbs: 68, fat: 22, category: 'Noodles', compatibleWith: ['halal'], isPopular: true,  macroDbRef: 'macro_laksa',    confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'fflak_meesiam', name: 'Mee Siam', emoji: '🍜', price: 4.00, calories: 450, protein: 16, carbs: 66, fat: 14, category: 'Noodles', compatibleWith: ['halal'], isPopular: false, macroDbRef: 'macro_mee_siam', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'foodfare_nasi_lemak_stall',
    name: 'Nasi Lemak',
    emoji: '🍚',
    cuisine: 'Malay',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['nasi lemak foodfare', 'foodfare nasi lemak'],
    dietTags: ['halal'],
    priceRange: '$',
    hawkerLocation: 'NTUC Foodfare',
    hawkerLocationId: 'ntuc_foodfare',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'ffnl_basic',   name: 'Nasi Lemak (basic)',      emoji: '🍚', price: 4.00, calories: 494, protein: 14, carbs: 60, fat: 22, category: 'Rice', compatibleWith: ['halal'], isPopular: true,  macroDbRef: 'macro_nasi_lemak',          confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'ffnl_chicken', name: 'Nasi Lemak with Chicken', emoji: '🍗', price: 5.50, calories: 680, protein: 30, carbs: 62, fat: 30, category: 'Rice', compatibleWith: ['halal'], isPopular: false, macroDbRef: 'macro_nasi_lemak_chicken', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'foodfare_drinks_stall',
    name: 'Drinks Corner',
    emoji: '☕',
    cuisine: 'Drinks',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['drinks foodfare', 'kopi foodfare'],
    dietTags: ['halal', 'vegan'],
    priceRange: '$',
    hawkerLocation: 'NTUC Foodfare',
    hawkerLocationId: 'ntuc_foodfare',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'ffdrk_kopi_o',    name: 'Kopi O',      emoji: '☕', price: 1.20, calories: 15,  protein: 0, carbs: 3,  fat: 0, category: 'Drinks', compatibleWith: ['vegan', 'halal', 'gluten_free', 'lactose_free'], isPopular: true,  macroDbRef: 'macro_kopi_o',     confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'ffdrk_teh_tarik', name: 'Teh Tarik',   emoji: '🥤', price: 1.50, calories: 112, protein: 4, carbs: 18, fat: 3, category: 'Drinks', compatibleWith: ['halal', 'gluten_free'],                           isPopular: true,  macroDbRef: 'macro_teh_tarik', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'ffdrk_milo',      name: 'Milo (Hot)',  emoji: '🥤', price: 1.60, calories: 140, protein: 3, carbs: 26, fat: 3, category: 'Drinks', compatibleWith: ['halal', 'gluten_free'],                           isPopular: false, macroDbRef: 'macro_milo',      confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // BANQUET (Hawker Management Pte Ltd)
  // ═══════════════════════════════════════════════════════════════

  {
    id: 'banquet_chicken_rice_stall',
    name: 'Chicken Rice Stall',
    emoji: '🍗',
    cuisine: 'Chinese',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['chicken rice banquet', 'banquet chicken rice'],
    dietTags: ['lactose_free'],
    priceRange: '$',
    hawkerLocation: 'Banquet',
    hawkerLocationId: 'banquet',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'banqcr_steamed', name: 'Steamed Chicken Rice', emoji: '🍗', price: 4.00, calories: 607, protein: 35, carbs: 74, fat: 17, category: 'Rice', compatibleWith: ['lactose_free'], isPopular: true,  macroDbRef: 'macro_chicken_rice_steamed',  confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'banqcr_roasted', name: 'Roasted Chicken Rice', emoji: '🍗', price: 4.00, calories: 650, protein: 36, carbs: 76, fat: 20, category: 'Rice', compatibleWith: ['lactose_free'], isPopular: false, macroDbRef: 'macro_chicken_rice_roasted', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'banquet_mixed_veg_rice_stall',
    name: 'Mixed Veg Rice',
    emoji: '🍱',
    cuisine: 'Local',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['cai png banquet', 'economy rice banquet', 'mixed rice banquet'],
    dietTags: ['vegetarian', 'halal'],
    priceRange: '$',
    hawkerLocation: 'Banquet',
    hawkerLocationId: 'banquet',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'banqmvr_2dish', name: 'Mixed Veg Rice (2 dishes)', emoji: '🍱', price: 3.50, calories: 390, protein: 14, carbs: 55, fat: 12, category: 'Rice', compatibleWith: ['vegetarian'], isPopular: false, macroDbRef: 'macro_mixed_veg_rice_2', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'banqmvr_3dish', name: 'Mixed Veg Rice (3 dishes)', emoji: '🍱', price: 4.50, calories: 480, protein: 18, carbs: 65, fat: 16, category: 'Rice', compatibleWith: ['vegetarian'], isPopular: true,  macroDbRef: 'macro_mixed_veg_rice_3', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'banquet_noodle_stall',
    name: 'Noodle Stall',
    emoji: '🍜',
    cuisine: 'Chinese',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['noodle banquet', 'wonton mee banquet', 'ban mian banquet'],
    dietTags: ['lactose_free'],
    priceRange: '$',
    hawkerLocation: 'Banquet',
    hawkerLocationId: 'banquet',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'banqnod_wonton',   name: 'Wonton Mee (Dry)', emoji: '🍜', price: 4.00, calories: 434, protein: 22, carbs: 58, fat: 12, category: 'Noodles', compatibleWith: ['lactose_free'], isPopular: true,  macroDbRef: 'macro_wonton_mee', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'banqnod_ban_mian', name: 'Ban Mian',          emoji: '🍜', price: 4.50, calories: 460, protein: 22, carbs: 64, fat: 12, category: 'Noodles', compatibleWith: ['lactose_free'], isPopular: false, macroDbRef: 'macro_ban_mian',   confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'banquet_laksa_stall',
    name: 'Laksa Corner',
    emoji: '🍲',
    cuisine: 'Local',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['laksa banquet', 'banquet laksa'],
    dietTags: ['halal'],
    priceRange: '$',
    hawkerLocation: 'Banquet',
    hawkerLocationId: 'banquet',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'banqlak_laksa', name: 'Laksa', emoji: '🍲', price: 4.50, calories: 589, protein: 27, carbs: 68, fat: 22, category: 'Noodles', compatibleWith: ['halal'], isPopular: true, macroDbRef: 'macro_laksa', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'banquet_nasi_lemak_stall',
    name: 'Nasi Lemak',
    emoji: '🍚',
    cuisine: 'Malay',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['nasi lemak banquet', 'banquet nasi lemak'],
    dietTags: ['halal'],
    priceRange: '$',
    hawkerLocation: 'Banquet',
    hawkerLocationId: 'banquet',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'banqnl_basic',   name: 'Nasi Lemak (basic)',      emoji: '🍚', price: 4.00, calories: 494, protein: 14, carbs: 60, fat: 22, category: 'Rice', compatibleWith: ['halal'], isPopular: true,  macroDbRef: 'macro_nasi_lemak',          confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'banqnl_chicken', name: 'Nasi Lemak with Chicken', emoji: '🍗', price: 5.50, calories: 680, protein: 30, carbs: 62, fat: 30, category: 'Rice', compatibleWith: ['halal'], isPopular: false, macroDbRef: 'macro_nasi_lemak_chicken', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },

  {
    id: 'banquet_drinks_stall',
    name: 'Drinks Corner',
    emoji: '☕',
    cuisine: 'Drinks',
    serviceTypes: ['dine_in', 'grab_go'],
    tier: 'estimated_menu',
    outletType: 'food_court_stall',
    sfaLicenceType: 'food_stall',
    aliases: ['drinks banquet', 'kopi banquet', 'teh banquet'],
    dietTags: ['halal', 'vegan'],
    priceRange: '$',
    hawkerLocation: 'Banquet',
    hawkerLocationId: 'banquet',
    lastUpdated: '2026-08-07',
    menu: [
      { id: 'banqdrk_kopi_o',    name: 'Kopi O',      emoji: '☕', price: 1.20, calories: 15,  protein: 0, carbs: 3,  fat: 0, category: 'Drinks', compatibleWith: ['vegan', 'halal', 'gluten_free', 'lactose_free'], isPopular: true,  macroDbRef: 'macro_kopi_o',     confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'banqdrk_teh_tarik', name: 'Teh Tarik',   emoji: '🥤', price: 1.50, calories: 112, protein: 4, carbs: 18, fat: 3, category: 'Drinks', compatibleWith: ['halal', 'gluten_free'],                           isPopular: true,  macroDbRef: 'macro_teh_tarik', confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
      { id: 'banqdrk_milo',      name: 'Milo (Hot)',  emoji: '🥤', price: 1.60, calories: 140, protein: 3, carbs: 26, fat: 3, category: 'Drinks', compatibleWith: ['halal', 'gluten_free'],                           isPopular: false, macroDbRef: 'macro_milo',      confidence: 'estimated', source: 'hpb', verified: false, lastVerified: '2026-08-07' },
    ],
  },
];
